### PR TITLE
Resolved most deprecation warnings

### PR DESCRIPTION
**Pull request by charliekmorris**
I hate hiding warnings/errors but these ones were driving me crazy, so I went through and fixed up all the deprecation warnings I could find. There's still two (that I found) out there that I couldn't figure out how to fix, but this clears up most of them.

### CODE REVIEW

**Comment by minimaxir** [comment]
Does fixing these depreciations allow TF 2.0 to load the package? I'll have to test that.

Thanks for this! This is extremely helpful :)

**Comment by charliekmorris** [comment]
As it stands I think not, but let me play with it a bit, I may be able to get that running

**Comment by charliekmorris** [comment]
I've added a few more changes to make it closer to v 2.0 compatible, but it's not quite there yet. All of tf.contrib has been deprecated including HParams which you use fairly heavily, removing that will take some more dramatic code rewriting

**Comment by charliekmorris** [comment]
This one is over my head but it's an issue tensorflow is aware of. It's an issue being tracked here: https://github.com/tensorflow/tensorflow/issues/30418

**Comment by minimaxir** [comment]
Nonpythonic implementations are fine.

I'll give this a test and merge when I can! (this is a big enough change to bump to 0.6.0)

**Comment by minimaxir** [comment]
LGTM in my testing. It doesn't appear anything's broken.

Yes, it's not fully 2.0 compatible, but this is a big step! Thanks! I'll keep an eye on that issue and see if there's a workaround.

**Pull request merged**
